// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
)

type List struct {
	ListID   int32          `json:"list_id"`
	ListName sql.NullString `json:"list_name"`
}

type Task struct {
	TaskID      int32          `json:"task_id"`
	ListID      sql.NullInt32  `json:"list_id"`
	Description sql.NullString `json:"description"`
	Done        sql.NullBool   `json:"done"`
	CreateAt    sql.NullTime   `json:"create_at"`
	UpdateAt    sql.NullTime   `json:"update_at"`
}
